### ISSUE TITLE
Clean up credentials parsing from config

### ISSUE THREAD

**Issue by miraclx** [calimero-network/core#1135]
Consider this from the config file:

```toml
[context.config.signer.relayer]
url = "http://3.125.79.112:63529/"

[context.config.near]
signer = "relayer"
protocol = "near"
network = "testnet"
contract_id = "calimero-context-config.testnet"

[context.config.signer.self.near.mainnet]
rpc_url = "https://rpc.mainnet.near.org/"
account_id = "60c257e5ab83bc594181d6b57b60af51c25e0e6774d99e01d3c5f58a4a66964c"
public_key = "ed25519:7Wi1zxHUqK5fz34UXHzVGb4nmbXiCPmGh4KdPx9ucHjH"
secret_key = "ed25519:<snip>"

[context.config.signer.self.near.testnet]
rpc_url = "https://rpc.testnet.near.org/"
account_id = "d2c930d3393621716f60222a1474c17ec586148edafeaafce2738c328390eb46"
public_key = "ed25519:FBpYwJayAt9e5JULa8EFSoyHoioGEnebq2E9EdsL9oMP"
secret_key = "ed25519:<snip>"
```

The following behaviour is expected:

1. For any protocol where the `account_id` is represented exactly the same as the `public_key`, we skip including the `public_key`.
2. When parsing the config, the [current logic](https://github.com/calimero-network/core/blob/2ee05c27a17fe80305a4479cee869af45c3cc07b/crates/context/config/src/client.rs#L60-L63) selects the `context.config.<protocol>` entry only when at least one `context.config.signer.self.<protocol>.<network>` entry exists, this is wrong! It means if `context.config.<protocol>.signer` == `"local"` and there are no credentials, it will still fallback to the relayer, which is unexpected behaviour. Instead it should make sure local credentials are available if and only if `context.config.<protocol>.signer` == `"local"`.
3. Remove the `Credentials` enum that attempts to parse each protocol's credentials, falling back to the next. As this requires we encode strict parsing to ensure a N+1 protocol's credentials don't mistakenly parse as N. Which may not always be possible as all the constraints may just be the same on two separate protocols (or they may share the same types. For example `ed25519_dalek::VerifyingKey`.
