### ISSUE TITLE
chore(config): remove protocol duplication in context config

### ISSUE THREAD

**Issue by miraclx** [calimero-network/core#1149]
As noted in https://github.com/calimero-network/core/pull/1148#discussion_r1995928083

We have an unnecessary duplication in the config specification

For example:

```toml
[context.config.near]
signer = "relayer"
protocol = "near"
network = "testnet"
contract_id = "calimero-context-config.testnet"
```

the `protocol` field is redundant (already named in the table)
